# SonarQube configuration
sonar.projectKey=fintech-app
sonar.projectName=FinTech Application
sonar.projectVersion=1.0

# Path to source directories 
sonar.sources=app/src/main/java
sonar.language=java
sonar.java.binaries=app/target/classes

# Path to test directories
sonar.tests=app/src/test/java
sonar.junit.reportPaths=app/target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=app/target/site/jacoco/jacoco.xml

# Exclude classes from coverage
sonar.coverage.exclusions=**/config/**,**/*Exception*.*
