server.port=8080
spring.application.name=fintech-app

# Actuator Endpoints for Kubernetes
management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.metrics.tags.application=${spring.application.name}
