apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintech-app-canary
  labels:
    app: fintech-app
    track: canary
spec:
  replicas: 1 # Only 1 replica for canary to test traffic
  selector:
    matchLabels:
      app: fintech-app
      track: canary
  template:
    metadata:
      labels:
        app: fintech-app
        track: canary
    spec:
      containers:
      - name: fintech-app
        image: my-docker-registry/fintech-app:v1.1.0-canary
        ports:
        - containerPort: 8080
